name: jahnhalle
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  scrollable_positioned_list: ^0.3.8
  provider: ^6.1.2
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  timeline_tile: ^2.0.0
  sign_in_with_apple: ^6.1.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.1
  flutter_stripe: ^10.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/profile.png
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roquefort
      fonts:
        - asset: assets/fonts/Roquefort-Standard.ttf
